inherit_from:
  - .rubocop_todo.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/main/.rubocop-factory_bot.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/main/.rubocop-performance.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/main/.rubocop-rails.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/main/.rubocop-rake.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/main/.rubocop-rspec_rails.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/main/.rubocop-rspec.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/main/.rubocop.yml

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Metrics/ParameterLists:
  Max: 6

Rails/ApplicationRecord:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
